#!/usr/bin/env python

import util
import sys
import os

printf = util.printf

if __name__ == "__main__":
    if len(sys.argv)>=2:
        client = util.IpReporterClient(conf_file=sys.argv[1])
    else:
        client = util.IpReporterClient()
    for (k,v,m) in client.delAll():
        printf("%s: %s %s\n",k,v,m)
