#!/usr/bin/env python

import util
import sys
import os

printf = util.printf

if __name__ == "__main__":
    if len(sys.argv)>=2:
        client = util.IpReporterClient(conf_file=sys.argv[1])
    else:
        client = util.IpReporterClient()
    ips = sorted(client.getAll())
    for (k,v) in ips:
        printf("%s: %s\n",k,v)
