#!/usr/bin/env python

import util
import sys
import os

printf = util.printf

def usage(prog):
    printf("usage is %s <name>\n",prog);
    printf("\n")
    printf("set the name to the ip address useing the config file\n")
    printf("~/ipreporter.json")

if __name__ == "__main__":
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<2:
        usage(prog)
        sys.exit()

    client = util.IpReporterClient()
    name = sys.argv[1]
    printf("%s: %s\n",name,client.getIp(name))
